from typing import Any, Dict
from fhk.obj import Subset

__all__ = (
    "interval",
    "space",
    "LuaError",
    "Mem",
)

class Mem:
    def reset(self): ...

class LuaError(RuntimeError): ...

class Pin: ...

class LuaState:
    def new(self, view: Any) -> int: ...
    def solver(self, state: int, roots: Any) -> int: ...
    def read(self, state: int, fname: str): ...
    def ready(self, state: int) -> Pin: ...
    def pinsolver(self, state: int, idx: int) -> Pin: ...
    def callinit(self, init: Pin, mem: Mem, state: int) -> Pin: ...
    def callsolver(self, fn: Pin, solver: Pin, state: Any, result: Any, subset: Dict[str, Subset]): ...
    def unref(self, ref: int): ...

def interval(start: int, num: int) -> int: ...
def space(num: int) -> int: ...
