from typing import Any, Dict, Iterator, List, Sequence, TypeVar
from fhk.obj import Conv, Subset

__all__ = (
    "interval",
    "space",
    "Mem",
    "SolverState"
)

X = TypeVar("X")

def interval(start: int, num: int) -> int: ...
def space(num: int) -> int: ...
def isunit(ss: int) -> bool: ...
def subsetstr(ss: Subset) -> str: ...
def seq_iterss(mem: Sequence[X], ss: Subset) -> Iterator[X]: ...

class GCPin:
    def __getattr__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setattr__(self, key: Any, value: Any): ...
    def __setitem__(self, key: Any, value: Any): ...
    def __call__(self, *args: Any) -> Any: ...

class GCLua:
    fhk_py: GCPin

class Mem:
    def reset(self): ...

class GCDriver: ...

class CRoot:
    def __init__(self, name: str, conv: Conv, idx: int): ...

class SolverState:
    X: object
    inst: int

def newlua() -> GCPin: ...
def ready(state: GCPin) -> GCDriver: ...
def init(driver: GCDriver, gcm: Mem, X: Any) -> SolverState: ...
def solve(
    driver: GCDriver,
    solver: SolverState,
    roots: List[CRoot],
    subsets: Dict[str, Subset],
    result: Any
): ...
