from typing import Any, Callable, Generic, Iterable, Optional, Type, TypeVar

_T = TypeVar("_T")

__version__: str

class FhkError(Exception):
    ...

class GCLua:
    ...

class Mem:
    def reset(self) -> None: ...
    def destroy(self) -> None: ...

class Solver:
    ...

Subset = int | Iterable[int]
EMPTYSET = -1

class QueryFn(Generic[_T]):
    def __call__(
        self,
        state: Any = None,
        *,
        solver: Optional[Solver] = None,
        mem: Optional[Mem] = None,
        subsets: Optional[dict[str, Subset]] = None
    ) -> _T: ...

# This is a lie.
# `root` is actually a class.
# but this makes typecheckers happy when root is used as an annotation like:
#
#   class MyQuery:
#     xs: list[float] = root("x")
def root(name: str) -> Any: ...

class Graph:
    def __init__(self, *files: str, lua: Optional[GCLua] = None): ...
    def __enter__(self) -> "Graph": ...
    def __exit__(self, cls, val, tb) -> None: ...
    def read(self, *files: str) -> None: ...
    def ldef(self, src: str) -> None: ...
    def query(self, cls: Type[_T]) -> QueryFn[_T]: ...
    def add_given(self, var: str, f: Callable, ldef: Optional[str] = None) -> None: ...
    def given(self, var: str, *, ldef: Optional[str] = None) -> Callable[[Callable], None]: ...
    def add_model(self, f: Callable, name: Optional[str] = None, ldef: Optional[str] = None) -> None: ...
    def model(self, name: Optional[str] = None, ldef: Optional[str] = None) -> Callable[[Callable], None]: ...
    def prepare(self) -> None: ...
    def dump(self, color: bool = False) -> str: ...
    def sethook(self, hook: str) -> None: ...

def interval0(a: int, b: Optional[int] = None) -> int: ...
def interval1(a: int, b: Optional[int] = None) -> int: ...
